### ISSUE TITLE
Why the fork?

### ISSUE THREAD

**Issue by hanoii** [wpsvse/wpackagist#3]
Although it's a bit explained on the homepage I do wonder what was your motivation into forking a fairly popular repository for wordpress plugins. 

Please don't take this as a criticism, just truly wondering what your motivations were.

**Comment by khromov** [comment]
@hanoii We have great respect for the original authors. However, the original repository is currently not maintained well - issues are not answered and there hasn't been a single commit for over a year. That combined with multiple recent outages made us realize there should be an alternative.

Like stated in the readme, we hope to contribute bug fixes if the original project will take them. So far we've updated the dependencies, made the project PHP7 compatible, and are working on `mu-plugin` support and some edge cases around quirks in the plugin/theme repository process.

Hope that answers your question!

**Comment by hanoii** [comment]
Have you attempted to contact the original authors and maybe offer to take over? I guess you probably have.

I am always hesitant to use forks of popular option, I was hesitant outlandishideas/wpackagist as well but it seems the goto option.

It does answer the question though, so thanks.

**Comment by khromov** [comment]
@hanoii I don't want to step on any toes or take over any infrastructure that Outlandish runs. This is an independent project in the spirit of open source. Hopefully in the long run the original repo will incorporate some or all of our bugfixes, we will be sending pull requests.
